title: Zhengwei Chen
position: Ph.D. Student
affiliation: Purdue University
email: chen3413@purdue.edu
keywords: Microfluid, Optoelectrokinetic Particle Manipulation
google_scholar: https://scholar.google.com/citations?user=GqN6boYAAAAJ&hl
#github_link: https://github.com/yaoyao-liu/minimal-light
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/CZW.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/ZC.png
favicon_dark: ./assets/img/ZC.png
#description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
